name: Generate SBOM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install cyclonedx-npm
      run: npm install -g @cyclonedx/cyclonedx-npm

    - name: Generate SBOM
      run: cyclonedx-npm -o sbom.json

    - name: Show SBOM file
      run: cat sbom.json

